CREATE TABLE  "COMPONENT_MD" 
   (	"COMPONENTNO" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "COMPONENT_MD_PK" PRIMARY KEY ("COMPONENTNO")
  USING INDEX  ENABLE
   )
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_COMPONENT_MD" 
  before insert on "COMPONENT_MD"               
  for each row  
begin   
  if :NEW."COMPONENTNO" is null then 
    select "COMPONENT_MD_SEQ".nextval into :NEW."COMPONENTNO" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_COMPONENT_MD" ENABLE
/
