CREATE TABLE  "FLATPACK_MD" 
   (	"FLATPACKID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"COLOUR" VARCHAR2(50), 
	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"UNITPRICE" NUMBER(5,2) NOT NULL ENABLE, 
	 CONSTRAINT "FLATPACK_MD_PK" PRIMARY KEY ("FLATPACKID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FLATPACK_MD_CON" UNIQUE ("NAME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FLATPACK_MD_CN" CHECK ( "UNITPRICE" BETWEEN 5.00 and 500.00
) ENABLE, 
	 CONSTRAINT "FLATPACK_MD_CON1" CHECK ( "TYPE" in ('Office', 'Kitchen', 'Bedroom', 'General')) ENABLE
   )
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_FLATPACK_MD" 
  before insert on "FLATPACK_MD"               
  for each row  
begin   
  if :NEW."FLATPACKID" is null then 
    select "FLATPACK_MD_SEQ1".nextval into :NEW."FLATPACKID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_FLATPACK_MD" ENABLE
/