CREATE TABLE  "FLATPACKCOMPONENT_MD" 
   (	"FLATPACKID" NUMBER NOT NULL ENABLE, 
	"COMPONENTNO" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FLATPACKCOMPONENT_MD_CON" CHECK ( "QUANTITY" >0) ENABLE
   )
/
ALTER TABLE  "FLATPACKCOMPONENT_MD" ADD CONSTRAINT "COMPONENT_MD_FK" FOREIGN KEY ("COMPONENTNO")
	  REFERENCES  "COMPONENT_MD" ("COMPONENTNO") ENABLE
/
ALTER TABLE  "FLATPACKCOMPONENT_MD" ADD CONSTRAINT "FLATPACK_MD_FK" FOREIGN KEY ("FLATPACKID")
	  REFERENCES  "FLATPACK_MD" ("FLATPACKID") ENABLE
/
